### ISSUE TITLE
Refacto backend specification to support multiple-backends

### ISSUE THREAD

**Issue by hugoShaka** [hugoShaka/ansible-mailserver#78]
We should be able to specify multiple backend of multiple types (postgres, mysql, ldap, file, ...)
For example using variables, all the fields below are examples and implementation is free.
```
user_backends:
  - name: postgres database
    type: postgresql
    args:
      database: mailserver
      host: 10.0.0.1
      port: 5432
      user: mail
      password: "{{ mailserver_passwword }}"
  - name: legacy ldap backend
    type: ldap
    args:
      host: 10.0.0.2
      bind_dn: xxxx
      query: xxxx
      port: 636
```
